name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        zig-version: [0.13.0, master]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: ${{ matrix.zig-version }}

    - name: Run tests
      run: zig build test

    - name: Check compilation
      run: zig build check

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: 0.13.0

    - name: Check formatting
      run: zig fmt --check src/

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: 0.13.0

    - name: Build benchmark
      run: zig build -Doptimize=ReleaseFast

    - name: Run benchmark (if exists)
      run: |
        if [ -f "zig-out/bin/benchmark" ]; then
          ./zig-out/bin/benchmark
        else
          echo "No benchmark executable found, skipping benchmark run"
        fi
      continue-on-error: true
